name: Docker Dev Images Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'client/**'
      - 'packages/**'

jobs:
  check-dockerhub-secrets:
    runs-on: ubuntu-latest
    outputs:
      has_dockerhub_secrets: ${{ steps.check-dockerhub-secrets.outputs.has_dockerhub_secrets }}
    steps:
      - name: Check Docker Hub secrets
        id: check-dockerhub-secrets
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_TOKEN" ]; then
            echo "has_dockerhub_secrets=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_dockerhub_secrets=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: check-dockerhub-secrets
    if: ${{ needs.check-dockerhub-secrets.outputs.has_dockerhub_secrets == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: api-build
            file: Dockerfile.multi
            image_name: librechat-dev-api
          - target: node
            file: Dockerfile
            image_name: librechat-dev

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Prepare the environment
      - name: Prepare environment
        run: |
          cp .env.example .env

      # Build and push Docker images for each target
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.target }}
